apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: back-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ahmed324-ai/manifests'
    path: manifests/backend
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dependency-track
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
